on:
  workflow_call:
    inputs:
      app_id:
        required: true
        type: string
    secrets:
      private_key:
        required: true

# This workflow requires these permissions in the caller workflow.
# permissions:
#   actions: write
#   pull-requests: write
#   contents: write

jobs:
  fast-forward:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    name: Fast Forward
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: get-app-token
        with:
          app-id: ${{ inputs.app_id }}
          private-key: ${{ secrets.private_key }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          fetch-depth: 0

      - name: Get Pull Request
        id: get-pull-request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh api "/repos/${GITHUB_REPOSITORY}/pulls/${ISSUE_NUMBER}" \
            > pullRequest.json

          echo "BASE_REF=$(jq --raw-output '.base.ref' pullRequest.json)" \
            >> "${GITHUB_OUTPUT}"

          echo "HEAD_REF=$(jq --raw-output '.head.ref' pullRequest.json)" \
            >> "${GITHUB_OUTPUT}"

      - name: Fast Forward
        id: fast-forward
        continue-on-error: true
        env:
          BASE_REF: ${{ steps.get-pull-request.outputs.BASE_REF }}
          HEAD_REF: ${{ steps.get-pull-request.outputs.HEAD_REF }}
        run: |
          git checkout ${BASE_REF} \
            && git merge origin/${HEAD_REF} --ff-only \
            && git push origin ${BASE_REF}

      - name: Write Success Comment
        if: ${{ steps.fast-forward.outcome == 'success' }}
        run: |
          echo "**_Success!_** 💚" > pullRequestComment.md

      - name: Write Failure Comment
        if: ${{ steps.fast-forward.outcome == 'failure' }}
        run: |
          echo "**_Failure!_** 💥" > pullRequestComment.md

      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          BASE_REF: ${{ steps.get-pull-request.outputs.BASE_REF }}
          HEAD_REF: ${{ steps.get-pull-request.outputs.HEAD_REF }}
        run: |
          echo "Fast forward commits from ***${HEAD_REF}*** to ***${BASE_REF}***." \
          >> pullRequestComment.md

          gh pr comment ${ISSUE_NUMBER} \
            --body-file pullRequestComment.md
