on:
  workflow_call:
    inputs:
      workflow_name:
        required: false
        type: string
        default: "fast-forward"
      app_id:
        required: true
        type: string
    secrets:
      private_key:
        required: true

permissions:
  actions: write
  pull-requests: write
  contents: write

jobs:
  fast_forward_job:
    name: Fast Forward
    defaults:
      run:
        shell: bash
    env:
      FAST_FORWARD_PULL_REQUESTS_APP_ID: ${{ inputs.app_id }}
      FAST_FORWARD_PULL_REQUESTS_PRIVATE_KEY: ${{ secrets.private_key }}
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1
        id: app-token
        with:
          app-id: ${{ env.FAST_FORWARD_PULL_REQUESTS_APP_ID }}
          private-key: ${{ env.FAST_FORWARD_PULL_REQUESTS_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Get Pull Request
        id: get-pull-request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh api "/repos/${GITHUB_REPOSITORY}/pulls/${ISSUE_NUMBER}" \
            > pullRequest.json

          echo "BASE_REF=$(jq --raw-output '.base.ref' pullRequest.json)" \
            >> "${GITHUB_OUTPUT}"

          echo "HEAD_REF=$(jq --raw-output '.head.ref' pullRequest.json)" \
            >> "${GITHUB_OUTPUT}"

      - name: Fast Forward
        id: fast-forward
        continue-on-error: true
        env:
          BASE_REF: ${{ steps.get-pull-request.outputs.BASE_REF }}
          HEAD_REF: ${{ steps.get-pull-request.outputs.HEAD_REF }}
        run: |
          git checkout ${BASE_REF} \
            && git merge origin/${HEAD_REF} --ff-only \
            && git push origin ${BASE_REF}

      - name: Write Success Comment
        if: ${{ steps.fast-forward.outcome == 'success' }}
        run: |
          echo "**_Success!_** 💚" > pullRequestComment.md

      - name: Write Failure Comment
        if: ${{ steps.fast-forward.outcome == 'failure' }}
        run: |
          echo "**_Failure!_** 💥" > pullRequestComment.md

      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          BASE_REF: ${{ steps.get-pull-request.outputs.BASE_REF }}
          HEAD_REF: ${{ steps.get-pull-request.outputs.HEAD_REF }}
        run: |
          echo "Fast forward commits from ***${HEAD_REF}*** to ***${BASE_REF}***." \
          >> pullRequestComment.md

          cat --show-all pullRequestComment.md

          gh pr comment ${ISSUE_NUMBER} \
            --body-file pullRequestComment.md
